version: "3.8"

services:
  api-backend:
    build: ../../services/api-backend
    container_name: api_backend
    restart: unless-stopped
    network_mode: "host"
    environment:
      PORT: ${PORT:-3000}
      KAFKA_BROKER: ${KAFKA_BROKER:-127.0.0.1:9092}
      PGHOST: ${PGHOST:-127.0.0.1}
      PGDATABASE: ${PGDATABASE:-trafico_db}
      PGUSER: ${PGUSER:-postgres}
      PGPASSWORD: ${PGPASSWORD:-changeme}
      SQLI_DEMO: ${SQLI_DEMO:-false}
    volumes:
      - ./keys:/app/keys:ro
