#!/usr/sbin/nft -f

flush ruleset

table inet filter {
  chain input {
    type filter hook input priority 0; policy drop;

    iif "lo" accept
    ct state established,related accept
    ip protocol icmp accept

    tcp dport 22 ip saddr { TU_IP_ADMIN/32 } accept

    # API — only from nginx-proxy
    tcp dport 3000 ip saddr { 10.0.1.5 } accept

    log prefix "BACKEND-DENIED: " drop
  }

  chain forward {
    type filter hook forward priority 0; policy drop;
  }

  chain output {
    type filter hook output priority 0; policy accept;
  }
}
